
services:
  - type: web
    name: prometheus-backend
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y lua5.1
      npm install
    startCommand: npm start
